### ISSUE TITLE
undefined method `settings' for nil:NilClass

### ISSUE THREAD

**Issue by HatemMahmoud** [huerlisi/CyDoc#9]
Hi,

I just cloned the repo, run rake db:seed and created a new user using the console. Now trying to sign in gives this error:

Showing /Users/hatem/Projects/ExpressionLab/AlsahryCenter/CyDoc/app/views/layouts/application.html.haml where line #27 raised:

undefined method `settings' for nil:NilClass
Extracted source (around line #27):
```
24:             = t('application.title')
25: 
26:           - if user_signed_in?
27:             = render_navigation(:level => 1..2, :expand_all => true)
28:             = form_tag search_path, :method => :get, :class => "navbar-search pull-left" do
29:               = text_field_tag "query", params[:query], :placeholder => t('placeholder.search'), :class => "search-query"
30:             %div= render 'users/user_bar'
```

**Comment by huerlisi** [comment]
@HatemMahmoud is this still an issue?
